// <auto-generated />
using System;
using MachineBuildingFactory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineBuildingFactory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221210221806_Role-User-Admin-Management")]
    partial class RoleUserAdminManagement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a719be14-6ee5-4a10-a1b6-382fc43c4d0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "979b3458-70c1-44bc-a4da-0da23e72c052",
                            Department = 0,
                            Email = "peter@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Peter",
                            LastName = "Petrov",
                            LockoutEnabled = true,
                            NormalizedEmail = "PETER@ABV.BG",
                            NormalizedUserName = "PETER",
                            PasswordHash = "AQAAAAEAACcQAAAAEGd9Gm7qdn/MM8bnfeS9sudejYleVMQuqfFCu/D6RP6qXJNM02JuabwhF44YFXUd2A==",
                            Phone = "+3596598665",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fba8f29a-4b87-4314-8aec-8f99012a6fb6",
                            Signature = "PP",
                            Title = 2,
                            TwoFactorEnabled = false,
                            UserName = "peter"
                        },
                        new
                        {
                            Id = "a6fdd00e-8d80-4b98-894e-0fabfb3bab41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c70113d1-9d44-4e3a-b5a9-0abfd9ed1e62",
                            Department = 4,
                            Email = "georgi@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Georgi",
                            LastName = "Georgiev",
                            LockoutEnabled = true,
                            NormalizedEmail = "GEORGI@ABV.BG",
                            NormalizedUserName = "GEORGI",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3XMxW/2goicCSFcUZpKR+asqTRVFnEKL91LcKP0FQqGJUHNzmaEfFaPAoLJ/nAJA==",
                            Phone = "+3596578569",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97e3d486-6f05-4c68-9f39-a2bf9a871b4b",
                            Signature = "GG",
                            Title = 3,
                            TwoFactorEnabled = false,
                            UserName = "georgi"
                        },
                        new
                        {
                            Id = "3a36e169-5bc9-43c4-a3d1-72ed8aa46bc6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a4a0ead-4e48-4885-b904-8c114afa0785",
                            Department = 1,
                            Email = "todor@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Todor",
                            LastName = "Todorov",
                            LockoutEnabled = true,
                            NormalizedEmail = "TODOR@ABV.BG",
                            NormalizedUserName = "TODOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEKVpID4qZLxV/2/ECwdCGFDLz067oRczafmeKO4tQMzCRrOaicAZblZsllEFcEvb0A==",
                            Phone = "+3596573322",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06968b9c-2214-4641-9203-28d71cf54519",
                            Signature = "TT",
                            Title = 2,
                            TwoFactorEnabled = false,
                            UserName = "todor"
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ApplicationUserAssembly", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssemblyId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "AssemblyId");

                    b.HasIndex("AssemblyId");

                    b.ToTable("ApplicationUserAssemblies");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ApplicationUserWorkingAssembly", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssemblyId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "AssemblyId");

                    b.HasIndex("AssemblyId");

                    b.ToTable("ApplicationUserWorkingAssemblies");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorSignature")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Assemblies");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AuthorSignature = "GG",
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(3066),
                            Description = "Base support for hole construction",
                            DrawingNumber = "CW-001-00",
                            Image = "https://files.fm/thumb_show.php?i=e3en9mxbj",
                            Name = "Weld construction"
                        },
                        new
                        {
                            Id = 4,
                            AuthorSignature = "PP",
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(3070),
                            Description = "Rotational casting is the best way to make hollow resin parts",
                            DrawingNumber = "CF-050-00",
                            Image = "https://files.fm/thumb_show.php?i=rcgp3g9nf",
                            Name = "Rotational casting machine"
                        },
                        new
                        {
                            Id = 5,
                            AuthorSignature = "DD",
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(3073),
                            Description = "Steam turbine 100 kW",
                            DrawingNumber = "WM-026-100-R",
                            Image = "https://files.fm/thumb_show.php?i=rafszmvtu",
                            Name = "Steam turbine"
                        },
                        new
                        {
                            Id = 6,
                            AuthorSignature = "DD",
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(3077),
                            Description = "Cooling system for industry",
                            DrawingNumber = "CS-125-TF58-000",
                            Image = "https://files.fm/thumb_show.php?i=zqg8235n3",
                            Name = "Cooling system"
                        },
                        new
                        {
                            Id = 7,
                            AuthorSignature = "TT",
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(3111),
                            Description = "High pressure reciprocating compressor",
                            DrawingNumber = "CM-300-RF98-700",
                            Image = "https://files.fm/thumb_show.php?i=8ug7rbkqh",
                            Name = "Compressor"
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.AssemblyProductionPart", b =>
                {
                    b.Property<int>("AssemblyId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionPartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("AssemblyId", "ProductionPartId");

                    b.HasIndex("ProductionPartId");

                    b.ToTable("AssemblyProductionParts");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.AssemblyPurchasedPart", b =>
                {
                    b.Property<int>("AssemblyId")
                        .HasColumnType("int");

                    b.Property<int>("PurchasedPartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("AssemblyId", "PurchasedPartId");

                    b.HasIndex("PurchasedPartId");

                    b.ToTable("AssemblyPurchasedParts");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Email = "office@festo.com",
                            Name = "Festo",
                            UrlAddress = "Festo.com"
                        },
                        new
                        {
                            Id = 6,
                            Email = "office@sew.com",
                            Name = "SEW",
                            UrlAddress = "Sew.com"
                        },
                        new
                        {
                            Id = 7,
                            Email = "office@siemens.com",
                            Name = "Siemens",
                            UrlAddress = "SEW.com"
                        },
                        new
                        {
                            Id = 8,
                            Email = "office@valeo.com",
                            Name = "Valeo",
                            UrlAddress = "Valeo.com"
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaterialNumber = "1.0038"
                        },
                        new
                        {
                            Id = 2,
                            MaterialNumber = "1.8714"
                        },
                        new
                        {
                            Id = 3,
                            MaterialNumber = "1.5786"
                        },
                        new
                        {
                            Id = 4,
                            MaterialNumber = "1.4302"
                        },
                        new
                        {
                            Id = 5,
                            MaterialNumber = "1.7025"
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ProductionPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorSignature")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("ColorOfPaintRal")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("LaserCutLength")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("SurfaceArea")
                        .HasColumnType("float");

                    b.Property<int?>("SurfaceTreatment")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfPaint")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfProductionPartId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TypeOfProductionPartId");

                    b.ToTable("ProductionParts");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            AuthorSignature = "PP",
                            ColorOfPaintRal = 3,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2957),
                            Description = "This is just a probe part.",
                            DrawingNumber = "CL-025-001",
                            Image = "https://files.fm/thumb_show.php?i=wuvwwvyyu",
                            LaserCutLength = 4.2999999999999998,
                            MaterialId = 2,
                            Name = "Consol",
                            SurfaceArea = 2.2999999999999998,
                            SurfaceTreatment = 1,
                            TypeOfPaint = 2,
                            TypeOfProductionPartId = 1,
                            Weight = 5.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            AuthorSignature = "TT",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2964),
                            Description = "Shaft for all target.",
                            DrawingNumber = "CL-025-002",
                            Image = "https://files.fm/thumb_show.php?i=yanftmubg",
                            LaserCutLength = 5.9000000000000004,
                            MaterialId = 3,
                            Name = "Shaft",
                            SurfaceArea = 1.3,
                            SurfaceTreatment = 2,
                            TypeOfPaint = 3,
                            TypeOfProductionPartId = 2,
                            Weight = 8.5999999999999996
                        },
                        new
                        {
                            Id = 7,
                            AuthorSignature = "DD",
                            ColorOfPaintRal = 3,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2969),
                            Description = "For all type of construction",
                            DrawingNumber = "BP-080-008",
                            Image = "https://files.fm/thumb_show.php?i=avqbb8jgk",
                            LaserCutLength = 8.9000000000000004,
                            MaterialId = 5,
                            Name = "Base plate",
                            SurfaceArea = 5.2999999999999998,
                            SurfaceTreatment = 3,
                            TypeOfPaint = 2,
                            TypeOfProductionPartId = 2,
                            Weight = 12.6
                        },
                        new
                        {
                            Id = 8,
                            AuthorSignature = "TT",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2973),
                            Description = "Gear for gearbox",
                            DrawingNumber = "GB-200-036",
                            Image = "https://files.fm/thumb_show.php?i=n62awsh2s",
                            LaserCutLength = 0.0,
                            MaterialId = 4,
                            Name = "Gear 34/69",
                            SurfaceArea = 8.3000000000000007,
                            SurfaceTreatment = 3,
                            TypeOfPaint = 1,
                            TypeOfProductionPartId = 1,
                            Weight = 6.5999999999999996
                        },
                        new
                        {
                            Id = 9,
                            AuthorSignature = "TT",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2978),
                            Description = "Brackets for Frame",
                            DrawingNumber = "GB-200-036",
                            Image = "https://files.fm/thumb_show.php?i=qjugekfuf",
                            LaserCutLength = 0.0,
                            MaterialId = 1,
                            Name = "Brackets",
                            SurfaceArea = 8.3000000000000007,
                            SurfaceTreatment = 3,
                            TypeOfPaint = 1,
                            TypeOfProductionPartId = 2,
                            Weight = 6.5999999999999996
                        },
                        new
                        {
                            Id = 10,
                            AuthorSignature = "GG",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2982),
                            Description = "Frame big size",
                            DrawingNumber = "FBS-2365-078",
                            Image = "https://files.fm/thumb_show.php?i=2y4zzx6pb",
                            LaserCutLength = 0.0,
                            MaterialId = 1,
                            Name = "Frame 1000x200",
                            SurfaceArea = 105.3,
                            SurfaceTreatment = 3,
                            TypeOfPaint = 1,
                            TypeOfProductionPartId = 3,
                            Weight = 6.5999999999999996
                        },
                        new
                        {
                            Id = 11,
                            AuthorSignature = "GG",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2986),
                            Description = "Toot 45, M=7, TRE-89",
                            DrawingNumber = "RW-859-026",
                            Image = "https://files.fm/thumb_show.php?i=8a2t5t9z9",
                            LaserCutLength = 0.0,
                            MaterialId = 1,
                            Name = "Rack-Wheel",
                            SurfaceArea = 1.2,
                            SurfaceTreatment = 1,
                            TypeOfPaint = 1,
                            TypeOfProductionPartId = 1,
                            Weight = 5.5999999999999996
                        },
                        new
                        {
                            Id = 12,
                            AuthorSignature = "GG",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2991),
                            Description = "Toot 65, M=4, SPG-05",
                            DrawingNumber = "RW-859-026",
                            Image = "https://files.fm/thumb_show.php?i=2gqgfmt48",
                            LaserCutLength = 0.0,
                            MaterialId = 1,
                            Name = "Sprocket",
                            SurfaceArea = 1.2,
                            SurfaceTreatment = 1,
                            TypeOfPaint = 1,
                            TypeOfProductionPartId = 1,
                            Weight = 5.5999999999999996
                        },
                        new
                        {
                            Id = 13,
                            AuthorSignature = "DD",
                            ColorOfPaintRal = 1,
                            CreatedOn = new DateTime(2022, 12, 10, 23, 18, 6, 130, DateTimeKind.Local).AddTicks(2995),
                            Description = "Thsi Part breaks the DetailView",
                            DrawingNumber = "BV-000-001",
                            Image = "https://files.fm/thumb_show.php?i=wzjth76ag",
                            LaserCutLength = 0.0,
                            MaterialId = 1,
                            Name = "Just Details",
                            SurfaceArea = 1.2,
                            SurfaceTreatment = 1,
                            TypeOfPaint = 1,
                            TypeOfProductionPartId = 2,
                            Weight = 5.5999999999999996
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.PurchasedPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Standard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchasedParts");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Description = "Gear motor of SEW, Supplier: Misumi",
                            Image = "https://files.fm/thumb_show.php?i=zbkja84dh",
                            ItemNumber = "GM-100/25-368A",
                            ManufacturerId = 5,
                            Name = "Gearbox",
                            Standard = "ISO 36264",
                            SupplierId = 12,
                            Weight = 56.799999999999997
                        },
                        new
                        {
                            Id = 6,
                            Description = "Compact cylinders ADN-S, double-acting",
                            Image = "https://files.fm/thumb_show.php?i=bduy24ra6",
                            ItemNumber = "ADN-S-12-25-I-P",
                            ManufacturerId = 6,
                            Name = "Compact cylinders ADN-S",
                            Standard = "ISO 21287",
                            SupplierId = 14,
                            Weight = 2.2999999999999998
                        },
                        new
                        {
                            Id = 7,
                            Description = "For material handling applications",
                            Image = "https://files.fm/thumb_show.php?i=a62t5h3r2",
                            ItemNumber = "SKF SY 35 TR",
                            ManufacturerId = 7,
                            Name = "Pillow block bearing",
                            Standard = "ISO 55629",
                            SupplierId = 13,
                            Weight = 1.3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Read holding registers (03) 29 words",
                            Image = "https://files.fm/thumb_show.php?i=sh76p8cgu",
                            ItemNumber = "ATV310",
                            ManufacturerId = 7,
                            Name = "Variable speed drive",
                            Standard = "ISO 32685",
                            SupplierId = 11,
                            Weight = 1.3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Linear Bearing with Round Flange",
                            Image = "https://files.fm/thumb_show.php?i=thrgt2tfr",
                            ItemNumber = "LMF 06UU",
                            ManufacturerId = 7,
                            Name = "Linear Bearing",
                            Standard = "ISO 36958",
                            SupplierId = 13,
                            Weight = 1.3
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Email = "office@norelem.com",
                            Name = "Norelem",
                            UrlAddress = "Norelem.com"
                        },
                        new
                        {
                            Id = 12,
                            Email = "office@misumi.com",
                            Name = "Misumi",
                            UrlAddress = "Misumi.com"
                        },
                        new
                        {
                            Id = 13,
                            Email = "office@maedler.com",
                            Name = "Maedler",
                            UrlAddress = "Maedler.com"
                        },
                        new
                        {
                            Id = 14,
                            Email = "office@haberkorn.com",
                            Name = "Haberkorn",
                            UrlAddress = "Haberkorn.com"
                        });
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.TypeOfProductionPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfProductionParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mechanically processed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sheet metal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Weld construction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lasercut"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cast"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "236787a2-4edc-492e-acb2-5f4a00ade9e3",
                            ConcurrencyStamp = "1",
                            Name = "Management",
                            NormalizedName = "Management"
                        },
                        new
                        {
                            Id = "cadc8910-5d74-4791-aad9-3523e2fd2468",
                            ConcurrencyStamp = "2",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "5602dd52-6eb5-46b5-8e80-c9f88650067e",
                            ConcurrencyStamp = "3",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a719be14-6ee5-4a10-a1b6-382fc43c4d0b",
                            RoleId = "236787a2-4edc-492e-acb2-5f4a00ade9e3"
                        },
                        new
                        {
                            UserId = "a6fdd00e-8d80-4b98-894e-0fabfb3bab41",
                            RoleId = "cadc8910-5d74-4791-aad9-3523e2fd2468"
                        },
                        new
                        {
                            UserId = "3a36e169-5bc9-43c4-a3d1-72ed8aa46bc6",
                            RoleId = "5602dd52-6eb5-46b5-8e80-c9f88650067e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ApplicationUserAssembly", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserAssemblys")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.Assembly", "Assembly")
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Assembly");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ApplicationUserWorkingAssembly", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("WorkingAssembly")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.Assembly", "Assembly")
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Assembly");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.AssemblyProductionPart", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.Assembly", "Assembly")
                        .WithMany("AssemblyProductionParts")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.ProductionPart", "ProductionPart")
                        .WithMany()
                        .HasForeignKey("ProductionPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("ProductionPart");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.AssemblyPurchasedPart", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.Assembly", "Assembly")
                        .WithMany("AssemblyPurchаsedParts")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.PurchasedPart", "PurchasedPart")
                        .WithMany()
                        .HasForeignKey("PurchasedPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("PurchasedPart");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ProductionPart", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.TypeOfProductionPart", "TypeOfProductionPart")
                        .WithMany()
                        .HasForeignKey("TypeOfProductionPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("TypeOfProductionPart");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.PurchasedPart", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineBuildingFactory.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MachineBuildingFactory.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserAssemblys");

                    b.Navigation("WorkingAssembly");
                });

            modelBuilder.Entity("MachineBuildingFactory.Data.Models.Assembly", b =>
                {
                    b.Navigation("AssemblyProductionParts");

                    b.Navigation("AssemblyPurchаsedParts");
                });
#pragma warning restore 612, 618
        }
    }
}
